### ISSUE TITLE
Enhancement - Removing same conversions

### ISSUE THREAD

**Issue by Aatmaj-Zephyr** [EshanTrivedi21/The-BaseChanger#4]
Remove the output dynamically on the change in input to remove situations like this
<img width="646" alt="image" src="https://user-images.githubusercontent.com/83284294/209642045-6e0f8f09-a4f0-4c68-8048-da450430f035.png">

**Comment by EshanTrivedi21** [comment]
well that's not quite possible because it would take much more power yet look weird and would increase unwanted line of code
